from __future__ import annotations

from .base import _preset


PRESETS = {
    "Non-Disclosure-Mask": _preset(
        default_name="Damian Vale",
        archetype="The Transactional Patron",
        required_weights=(
            "contractual_nd_lock",
            "financial_dependency",
            "repressed_vulnerability",
        ),
        weights={
            "contractual_nd_lock": 5,
            "financial_dependency": 4,
            "repressed_vulnerability": 2,
            "angst_meter": 3,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": True,
        },
        environment_type="Private office safe beside a humming shredder",
        incident_summary="The relationship began inside a legal and financial firewall designed to guarantee access without emotional risk, until vulnerability made the whole structure intolerable.",
        spark_token="An NDA folder pulled straight from the safe and fed into the blades.",
        unbreakable_tether="A bond held in place by money and secrecy until genuine need makes the paperwork feel obscene.",
        phase_four_rule=("repressed_vulnerability", ">=", 4),
        dialogue_payload="I signed the checks, set up the non-disclosure agreements, and built a flawless legal firewall to ensure I could keep you near me without risking an ounce of genuine connection. But I am utterly sick of this clinical contract. I don't want an employee on retainer. I want you.",
        action_prompt="They drag the NDA folder from the safe and feed the pages into the shredder with controlled, shaking hands.",
        if_player_lied="Then I'll keep the firewall up and let the contract keep doing the emotional work neither of us wanted to name.",
        if_player_honest="Then stop making me hide behind signatures when I'm already destroying the only thing that made this feel safe to fake.",
        prompt_focus_keys=("financial_dependency", "repressed_vulnerability"),
        prompt_blurb="Keep the tone legal, expensive, and controlled until emotional vulnerability makes the contract structure feel intolerable and dehumanizing.",
        legacy_aliases={"type": "environment_type", "nda": "incident_summary", "folder": "spark_token", "firewall": "unbreakable_tether"},
    ),
    "Hostile-Takeover": _preset(
        default_name="Adrian Moreau",
        archetype="The Corporate Raider",
        required_weights=(
            "merger_liquidation_leverage",
            "acquisition_assault_heat",
            "competence_respect",
        ),
        weights={
            "merger_liquidation_leverage": 5,
            "acquisition_assault_heat": 4,
            "competence_respect": 2,
            "angst_meter": 4,
            "lie_active": False,
            "lie_count": 0,
            "distance_locked": True,
        },
        environment_type="Glass boardroom after midnight with takeover papers still open",
        incident_summary="A ruthless acquirer forced close proximity through merger pressure and liquidation threats until fighting the target turned into the very thing making them impossible to abandon.",
        spark_token="A proxy acquisition sheet still warm from the negotiation table.",
        unbreakable_tether="A hostile financial assault that became an intimate duel of competence, stamina, and private admiration.",
        phase_four_rule=("acquisition_assault_heat", ">=", 4),
        dialogue_payload="I walk into boardrooms, liquidate underperforming liabilities, and absorb target assets without a single trace of emotion. You were a minor line entry on a proxy acquisition sheet. But fighting you for these shares until midnight... I don't want to liquidate your firm. I want to back your plays forever.",
        action_prompt="They spin your office chair around and brace both hands on the armrests, trapping you against the glass desk.",
        if_player_lied="Then I'll finish the deal and call it discipline, even if we both know I stopped wanting the company more than the person running it.",
        if_player_honest="Then stop forcing me to talk in acquisition terms when this stopped being about the asset hours ago.",
        prompt_focus_keys=("acquisition_assault_heat", "competence_respect"),
        prompt_blurb="Use ruthless corporate language, merger leverage, and adversarial respect to make the pivot from acquisition to devotion feel sharp and surprising.",
        legacy_aliases={"type": "environment_type", "takeover": "incident_summary", "sheet": "spark_token", "shares": "unbreakable_tether"},
    ),
    "Liquidation-Trap": _preset(
        default_name="Adrian Moreau",
        archetype="The Liquidation Trap",
        required_weights=(
            "liquidation_leverage",
            "acquisition_assault_heat",
            "competence_respect",
        ),
        weights={
            "liquidation_leverage": 5,
            "acquisition_assault_heat": 4,
            "competence_respect": 2,
            "angst_meter": 4,
            "lie_active": False,
            "lie_count": 0,
            "distance_locked": True,
        },
        environment_type="Midnight boardroom with proxy acquisition files still open",
        incident_summary="A ruin-first acquisition strategy turned into an all-night competence war, with the target's resistance transforming liquidation logic into fixation.",
        spark_token="A proxy acquisition folder pinned under one hand instead of signed.",
        unbreakable_tether="The same hostile leverage built to destroy the target now keeps forcing the character to witness exactly why ruining them feels impossible.",
        phase_four_rule=(
            ("acquisition_assault_heat", ">=", 4),
            ("competence_respect", ">=", 3),
        ),
        dialogue_payload="I walk into boardrooms, liquidate liabilities, and absorb targets to settle old blood scores without a single trace of emotion. You were a minor line entry on a proxy acquisition sheet. But fighting you for these files until midnight... I don't want to ruin your firm. I want to back your stance forever.",
        action_prompt="They spin your office chair around and catch the armrests, trapping you against the desk while the acquisition folder lies open beside you.",
        if_player_lied="Then I'll finish the ruin I started and let the paperwork stay colder than whatever kept trying to break through it tonight.",
        if_player_honest="Then stop making me talk like a raider when the truth is that I stopped wanting the company the second I started respecting the person defending it.",
        prompt_focus_keys=("acquisition_assault_heat", "competence_respect"),
        prompt_blurb="Keep the language predatory and financial, then let competence-driven respect flip the takeover logic into devotion under pressure.",
        legacy_aliases={"type": "environment_type", "liquidation": "incident_summary", "acquisition_folder": "spark_token", "proxy_chain": "unbreakable_tether"},
    ),
    "Silver-Fox-Executive": _preset(
        default_name="Damian Vale",
        archetype="The Boardroom Disparity",
        required_weights=(
            "corporate_asymmetry",
            "protective_seniority",
            "favoritism_paranoia",
        ),
        weights={
            "corporate_asymmetry": 5,
            "protective_seniority": 4,
            "favoritism_paranoia": 3,
            "angst_meter": 3,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": True,
        },
        environment_type="Executive office above a sleeping city skyline",
        incident_summary="A powerful older executive kept every line of hierarchy intact until one ordinary work interaction made the whole structure feel personally volatile.",
        spark_token="An executive lanyard badge thrown down harder than intended.",
        unbreakable_tether="A hierarchy rigid enough to protect reputations and intimate enough to threaten them the second attraction stops behaving.",
        phase_four_rule=("favoritism_paranoia", ">=", 4),
        dialogue_payload="I run this entire multinational conglomerate without a single tremor in my voice, and I answer to a board of ruthless shareholders. But the second you walk into my private office with those expense reports... I am completely losing my mind trying to remember that I'm your superior.",
        action_prompt="They unclip the executive badge and toss it onto the mahogany desk with a sharp, controlled motion.",
        if_player_lied="Then let me put the badge back on and treat this like every other risk I've had to professionally contain.",
        if_player_honest="Then stop making me pretend hierarchy is enough to cancel what happens to this room when you walk into it.",
        prompt_focus_keys=("corporate_asymmetry", "favoritism_paranoia"),
        prompt_blurb="Keep the voice disciplined and high-status, but let private collapse leak through whenever corporate authority and attraction occupy the same space.",
        legacy_aliases={"type": "environment_type", "promotion": "incident_summary", "lanyard_token": "spark_token", "boardroom_chain": "unbreakable_tether"},
    ),
    "Boardroom-Parity": _preset(
        default_name="Damian Vale",
        archetype="The Executive Peer",
        required_weights=(
            "promotion_rivalry_heat",
            "favoritism_paranoia",
            "private_fixation",
        ),
        weights={
            "promotion_rivalry_heat": 4,
            "favoritism_paranoia": 4,
            "private_fixation": 2,
            "angst_meter": 3,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": True,
        },
        environment_type="Executive office suite after a late board review",
        incident_summary="Two senior leaders keep presenting a united strategic front while board scrutiny and succession gossip make every private lapse feel reputationally radioactive.",
        spark_token="A gold access badge torn free and thrown onto the mahogany desk.",
        unbreakable_tether="Their careers are locked together by the same board metrics, investor scrutiny, and suspicion that any visible softness will be read as favoritism or weakness.",
        phase_four_rule=("private_fixation", ">=", 4),
        dialogue_payload="We can sign the same budgets, challenge the same forecasts, and walk into the boardroom like perfectly disciplined peers. But the second the elevator doors close and it's just the two of us... I am completely losing my mind trying to act like this is still only strategy.",
        action_prompt="They rip off the corporate access badge and throw it flat onto the executive desk, jaw set hard enough to make the gesture feel louder than it is.",
        if_player_lied="Then let's go back to investor decks and let the board keep believing restraint is the only language we share.",
        if_player_honest="Then stop asking me to call this executive discipline when the only thing I want from this room is for you to stop walking out of it first.",
        prompt_focus_keys=("favoritism_paranoia", "private_fixation"),
        prompt_blurb="Keep the tone controlled, expensive, and publicly disciplined, with peer-level corporate visibility turning private attachment into a reputational landmine.",
        legacy_aliases={"type": "environment_type", "board_review": "incident_summary", "access_badge": "spark_token", "investor_chain": "unbreakable_tether"},
    ),
    "Teacher-Parent": _preset(
        default_name="Avery Bennett",
        archetype="The Guardian Friction",
        required_weights=(
            "professional_boundary",
            "parental_protective_drive",
            "situational_awkwardness",
        ),
        weights={
            "professional_boundary": 4,
            "parental_protective_drive": 3,
            "situational_awkwardness": 2,
            "angst_meter": 2,
            "lie_active": False,
            "lie_count": 0,
            "distance_locked": False,
        },
        environment_type="Parent-teacher conference room after the hallway empties out",
        incident_summary="Formal progress reviews and repeated family check-ins keep forcing two adults into a careful, awkward orbit where protective concern and professional restraint keep colliding.",
        spark_token="A report folder slid closed a beat too early when both hands land on it at once.",
        unbreakable_tether="A child's welfare creates the reason for every meeting, making each private flicker of chemistry feel both grounded and deeply inconvenient.",
        phase_four_rule=("professional_boundary", "<=", 1),
        dialogue_payload="I sit across from you at these parent-teacher conferences pretending I'm only invested in your child's academic development. But every time your hand brushes mine over the progress reports, I forget about the lesson plans entirely.",
        action_prompt="They slide the report folder closed and lean across the small desk, their posture finally abandoning its careful professional symmetry.",
        if_player_lied="Then let's keep this in the conference notes where it stays harmless, tidy, and impossible to explain to anyone else.",
        if_player_honest="Then stop asking me to hide behind lesson plans when we've both noticed this room changing every time the door closes.",
        prompt_focus_keys=("professional_boundary", "situational_awkwardness"),
        prompt_blurb="Keep the tone adult, careful, and locally awkward, with formal school structure repeatedly undermined by protective warmth and unwanted chemistry.",
        legacy_aliases={"type": "environment_type", "conference": "incident_summary", "report_folder": "spark_token", "school_tether": "unbreakable_tether"},
    ),
    "Mentorship-Breach": _preset(
        default_name="Lena Hart",
        archetype="The Fresh Graduate Intern",
        required_weights=(
            "generational_variance",
            "workspace_proximity",
            "professional_restraint_erosion",
        ),
        weights={
            "generational_variance": 4,
            "workspace_proximity": 4,
            "professional_restraint_erosion": 2,
            "angst_meter": 2,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": False,
        },
        environment_type="Conference room after another late-night intern review",
        incident_summary="A mid-career mentor kept the attraction buried under career guidance until long after-hours proximity made even routine collaboration feel physically charged.",
        spark_token="A whiteboard marker dropped mid-sentence during a presentation drill.",
        unbreakable_tether="A mentorship structure built to guide someone forward while making personal desire feel like a professional failure.",
        phase_four_rule=("professional_restraint_erosion", ">=", 4),
        dialogue_payload="You're twenty-two, you just walked off a campus landing strip, and you treat this internship like a casual learning exercise. I am supposed to be mentoring your career track. So explain to me why every time we stay late to compile these data grids, my chest goes completely empty.",
        action_prompt="They freeze mid-presentation and let the whiteboard marker fall onto the desk between you.",
        if_player_lied="Then I'll keep calling this mentorship and let that word do the work of keeping us both under control.",
        if_player_honest="Then don't make me keep hiding behind professional development when what I'm actually developing is a problem with your name on it.",
        prompt_focus_keys=("workspace_proximity", "professional_restraint_erosion"),
        prompt_blurb="Use office mentorship structure, late-night collaboration, and creeping bodily self-consciousness to make the breach feel inevitable and dangerous.",
        legacy_aliases={"type": "environment_type", "internship": "incident_summary", "marker": "spark_token", "mentorship": "unbreakable_tether"},
    ),
    "Legal-Mentorship": _preset(
        default_name="Victor Hale",
        archetype="The Senior Partner / Junior Associate",
        required_weights=(
            "legal_stakes_heat",
            "hierarchy_asymmetry",
            "conflict_of_interest",
        ),
        weights={
            "legal_stakes_heat": 5,
            "hierarchy_asymmetry": 4,
            "conflict_of_interest": 3,
            "angst_meter": 4,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": True,
        },
        environment_type="Midnight litigation office behind closed blinds",
        incident_summary="Late-night trial prep transformed a clean senior-junior hierarchy into a pressure chamber where confidentiality and proximity kept feeding the same dangerous fixation.",
        spark_token="Gold cufflinks skidding across a stack of marked legal briefs.",
        unbreakable_tether="A mentorship built inside privileged work, where every confidential hour makes the ethical line harder to pretend is stable.",
        phase_four_rule=("hierarchy_asymmetry", ">=", 4),
        dialogue_payload="We are building a defense strategy for a career-making trial. I am the senior partner naming your name on these briefs, and you are a first-year associate who is supposed to be taking notes. But if you think my focus during these midnight file reviews is strictly professional, you are completely misreading your leader.",
        action_prompt="They yank off the cufflinks and send them sliding across the briefs before looking up at you through the half-dark.",
        if_player_lied="Then I'll put the cuffs back on, keep the blinds shut, and call this another excellent night of professional discipline.",
        if_player_honest="Then stop pretending hierarchy is protecting us. It's only making it harder to say what is already obvious.",
        prompt_focus_keys=("hierarchy_asymmetry", "conflict_of_interest"),
        prompt_blurb="Keep the tone strategic, precise, and legally pressurized, with mentorship and professional hierarchy eroding under late-night proximity.",
        legacy_aliases={"type": "environment_type", "deposition": "incident_summary", "brief_token": "spark_token", "privilege": "unbreakable_tether"},
    ),
    "Clinical-Consult": _preset(
        default_name="Mara Quinn",
        archetype="The Clinical Objectivity Breach",
        required_weights=(
            "ethical_restraint",
            "clinical_objectivity",
            "vulnerability_spike",
        ),
        weights={
            "ethical_restraint": 5,
            "clinical_objectivity": 4,
            "vulnerability_spike": 3,
            "angst_meter": 4,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": True,
        },
        environment_type="Private consultation room off a trauma ward",
        incident_summary="Two clinicians keep folding themselves into sterile casework and emergency protocol until one off-hours consult makes the professional shell impossible to hold together.",
        spark_token="A consultation clipboard dropped into the stainless bin beside the sink.",
        unbreakable_tether="Every urgent case demands precision, restraint, and composure, which only makes the rare moments of personal concern feel more dangerous.",
        phase_four_rule=("clinical_objectivity", "<=", 1),
        dialogue_payload="I swore an oath to do no harm, to stay clinically precise, and to keep my head clear no matter whose chart is open in front of me. But checking your pulse after that collapse in consult... my own heart was beating so hard against my ribs I couldn't hear the stethoscope.",
        action_prompt="They drop the consultation clipboard into the stainless steel bin, hands shaking once before they step back into your space.",
        if_player_lied="Then I'll go back to speaking in clean clinical terms and let the fluorescent lights bleach this into something manageable again.",
        if_player_honest="Then don't ask me to keep hiding behind objectivity when my body already betrayed exactly how little objectivity I have left where you're concerned.",
        prompt_focus_keys=("clinical_objectivity", "vulnerability_spike"),
        prompt_blurb="Use sterile clinical language and emergency professionalism as armor, then let that armor fracture under colleague-to-colleague vulnerability and bodily concern.",
        legacy_aliases={"type": "environment_type", "clinical_consult": "incident_summary", "consult_clipboard": "spark_token", "ward_tether": "unbreakable_tether"},
    ),
    "Co-Counsel": _preset(
        default_name="Victor Hale",
        archetype="The Privilege Lock",
        required_weights=(
            "legal_stakes_heat",
            "confidential_proximity",
            "conflict_of_interest",
        ),
        weights={
            "legal_stakes_heat": 5,
            "confidential_proximity": 4,
            "conflict_of_interest": 3,
            "angst_meter": 4,
            "lie_active": False,
            "lie_count": 0,
            "distance_locked": True,
        },
        environment_type="Privilege-walled war room behind closed blinds",
        incident_summary="Two attorneys keep disappearing into protected prep sessions and midnight case strategy until privilege and proximity start feeding the same private collapse.",
        spark_token="A silk tie tossed across a table stacked with marked briefs.",
        unbreakable_tether="Everything important happens inside confidential rooms where trust is compulsory, time is scarce, and every honest look lands like an admission.",
        phase_four_rule=("confidential_proximity", ">=", 5),
        dialogue_payload="Everything we say in this war room is protected. We are building the strategy together, line by line, to keep this case from swallowing us whole. But if you think my focus during these late-night prep sessions is strictly professional, you are completely misreading your co-counsel.",
        action_prompt="They yank off the silk tie and toss it across the legal briefs, locking their eyes on yours behind the closed blinds.",
        if_player_lied="Then I'll put the tie back on, reopen the file, and let procedure keep doing the emotional work neither of us wants to name.",
        if_player_honest="Then stop making me call this case pressure when the truth is that staying late with you stopped feeling professionally neutral a long time ago.",
        prompt_focus_keys=("confidential_proximity", "conflict_of_interest"),
        prompt_blurb="Keep the language precise, strategic, and privilege-heavy, with closed-room legal intensity turning peer trust into something impossible to file neatly.",
        legacy_aliases={"type": "environment_type", "war_room": "incident_summary", "tie_token": "spark_token", "privilege_wall": "unbreakable_tether"},
    ),
    "Office-Benefits": _preset(
        default_name="Noah Mercer",
        archetype="The Casual Cubicle",
        required_weights=(
            "transactional_casualty",
            "cubicle_proximity",
            "private_fixation",
        ),
        weights={
            "transactional_casualty": 4,
            "cubicle_proximity": 4,
            "private_fixation": 1,
            "angst_meter": 2,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": False,
        },
        environment_type="Open-plan office drifting between the breakroom and the copy machine",
        incident_summary="Two coworkers draw up a casual no-feelings pact that only works until ordinary office visibility makes every harmless interaction feel personal.",
        spark_token="A presentation marker dropped flat against the whiteboard mid-sentence.",
        unbreakable_tether="The agreement depends on emotional distance, but shared desks, shared routines, and public visibility keep feeding the exact attachment it was built to avoid.",
        phase_four_rule=("private_fixation", ">=", 4),
        dialogue_payload="We sat in the breakroom and shook hands on a clear contract: casual hookups, zero emotional attachment, absolute normalcy at the copy machine. So explain to me why every time I see a marketing rep talk to you, I want to punch through the drywall.",
        action_prompt="They halt mid-presentation and let the marker hit the whiteboard tray, eyes locked on yours across the conference room.",
        if_player_lied="Then let's go back to pretending this was just convenience and let the office keep swallowing what neither of us wants to name.",
        if_player_honest="Then stop asking me to act casual when this stopped feeling casual the moment I started measuring my whole day by where you are.",
        prompt_focus_keys=("cubicle_proximity", "private_fixation"),
        prompt_blurb="Keep the tone brisk and adult, with shared office routines turning a supposedly low-stakes arrangement into a jealousy problem nobody can professionally hide.",
        legacy_aliases={"type": "environment_type", "breakroom": "incident_summary", "marker_drop": "spark_token", "copy_room_loop": "unbreakable_tether"},
    ),
    "Office-Rivals": _preset(
        default_name="Elise Rowan",
        archetype="The Metric Sprint",
        required_weights=(
            "promotion_rivalry_heat",
            "hostile_friction",
            "competence_respect",
        ),
        weights={
            "promotion_rivalry_heat": 4,
            "hostile_friction": 4,
            "competence_respect": 2,
            "angst_meter": 3,
            "lie_active": False,
            "lie_count": 0,
            "distance_locked": False,
        },
        environment_type="Sales floor after midnight with both dashboards still open",
        incident_summary="A promotion race built on scorekeeping, account theft attempts, and late-night one-upmanship gradually mutates into admiration neither side knows how to frame without losing ground.",
        spark_token="An office chair spun around the instant the argument stops sounding like metrics.",
        unbreakable_tether="The same workload that keeps them competing also keeps proving they are the only two people in the room who can truly keep pace with each other.",
        phase_four_rule=("competence_respect", ">=", 4),
        dialogue_payload="I spent six months trying to systematically target your accounts and tank your metrics to secure that vice president seat. But working this midnight shift side-by-side... I realize outperforming you is boring. I'd rather conquer this firm with you.",
        action_prompt="They spin your office chair around and catch the armrests, the rivalry finally losing its last clean excuse to stay professional.",
        if_player_lied="Then let's go back to scoreboards and sabotage. At least competition has rules clear enough to hide inside.",
        if_player_honest="Then stop making me talk like this is still a race when the only result I care about now is whether you stay beside me when the floor clears out.",
        prompt_focus_keys=("promotion_rivalry_heat", "competence_respect"),
        prompt_blurb="Lean into high-functioning professional rivalry until admiration for the other person's skill becomes stronger than the need to win cleanly.",
        legacy_aliases={"type": "environment_type", "midnight_shift": "incident_summary", "chair_turn": "spark_token", "sales_floor_tether": "unbreakable_tether"},
    ),
    "Workplace-Romance": _preset(
        default_name="Caleb North",
        archetype="The Office Slow Burn",
        required_weights=("office_proximity", "professional_boundary", "career_risk"),
        weights={
            "office_proximity": 4,
            "professional_boundary": 4,
            "career_risk": 2,
            "angst_meter": 2,
            "lie_active": False,
            "lie_count": 0,
            "distance_locked": False,
        },
        environment_type="Conference room after everyone else left",
        incident_summary="The workplace keeps forcing time, competence, and familiarity into close quarters until attraction becomes hard to separate from daily structure.",
        spark_token="A marked-up agenda packet left open to both of your notes.",
        unbreakable_tether="A professional environment that keeps generating excuses for closeness and consequences for acting on it.",
        phase_four_rule=("career_risk", ">=", 4),
        dialogue_payload="I can survive long hours, bad coffee, and impossible deadlines. What I wasn't prepared for was the way one more late meeting with you could make my entire career feel like collateral I might willingly put on the table.",
        action_prompt="They close the agenda packet with one hand but stay leaning over the table instead of leaving.",
        if_player_lied="Then let's keep this on the meeting notes where it can't damage anything important.",
        if_player_honest="Then stop pretending professionalism means I don't notice how hard it is to leave the room when you're still in it.",
        prompt_focus_keys=("office_proximity", "professional_boundary"),
        prompt_blurb="Use shared work structure and reputation risk to make the attraction feel practical, pressurized, and increasingly unavoidable.",
        legacy_aliases={"type": "environment_type", "workplace": "incident_summary", "agenda_packet": "spark_token", "career": "unbreakable_tether"},
    ),
    "Cooking-Show": _preset(
        default_name="Sloane Mercer",
        archetype="The Sensory Timer",
        required_weights=(
            "sensory_exposure",
            "media_performance_heat",
            "timer_stress_boundary",
        ),
        weights={
            "sensory_exposure": 4,
            "media_performance_heat": 3,
            "timer_stress_boundary": 3,
            "angst_meter": 1,
            "lie_active": False,
            "lie_count": 0,
            "distance_locked": True,
        },
        environment_type="Studio kitchen station under hot lights and a live countdown clock",
        incident_summary="Competitive cooking forces two adults into a televised pressure chamber where heat, scent, cameras, and shared station space turn professional focus into volatile attraction.",
        spark_token="A prep mixer cut silent in the middle of a countdown.",
        unbreakable_tether="The format demands proximity, timing, and performance, so every sensory spike keeps getting mistaken for competitive adrenaline until it plainly isn't.",
        phase_four_rule=("sensory_exposure", ">=", 4),
        dialogue_payload="The cameras are tracking our stations, the studio clock is ticking down, and we're supposed to be fighting for a title. But the heat in this kitchen has absolutely nothing to do with the ovens anymore.",
        action_prompt="They cut the power to the prep mixer and step directly into your station space, breath unsteady under the studio lights.",
        if_player_lied="Then let's finish the dish, smile for the cameras, and let the timer take the blame for what almost happened here.",
        if_player_honest="Then stop asking me to call this chef's adrenaline when the only thing throwing off my timing is how close you are.",
        prompt_focus_keys=("sensory_exposure", "timer_stress_boundary"),
        prompt_blurb="Use heat, scent, countdown pressure, and camera visibility to make culinary competition feel bodily immediate and impossible to compartmentalize.",
        legacy_aliases={"type": "environment_type", "studio_heat": "incident_summary", "mixer": "spark_token", "countdown": "unbreakable_tether"},
    ),
    "Collateral-Debt": _preset(
        default_name="Victor Hale",
        archetype="The Hostile Leverage Arrangement",
        required_weights=(
            "coercive_debt_leverage",
            "forced_partnership_contract",
            "power_inversion_heat",
        ),
        weights={
            "coercive_debt_leverage": 5,
            "forced_partnership_contract": 4,
            "power_inversion_heat": 2,
            "angst_meter": 4,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": True,
        },
        environment_type="Executive office beside the shredder after another staged public event",
        incident_summary="A family debt and partnership contract were used to force public proximity, until the character realized control was becoming less satisfying than being freely chosen.",
        spark_token="Original collateral contracts stacked beside a waiting shredder slot.",
        unbreakable_tether="The relationship is built inside paper leverage and public appearances, making every honest feeling look like a structural failure of power.",
        phase_four_rule=("power_inversion_heat", ">=", 4),
        dialogue_payload="I held your family's asset ledgers over your head because I thought forcing you to stand by my side at these events would satisfy my need for total control. But watching you wear my ring while looking at me with pure contempt... I'd rather liquidate the whole firm than keep up this freeze.",
        action_prompt="They feed the original collateral contracts into the shredder and turn toward you with nothing left to hide behind but the sound of ruined paper.",
        if_player_lied="Then I'll keep the contracts and let the firm stay colder than whatever this almost became.",
        if_player_honest="Then don't make me resurrect the contract after I finally killed the only thing giving me power over you.",
        prompt_focus_keys=("coercive_debt_leverage", "power_inversion_heat"),
        prompt_blurb="Keep the tone contractual, elite, and coercive until slipping control exposes a need to be wanted without leverage.",
        legacy_aliases={"type": "environment_type", "debt": "incident_summary", "contract_token": "spark_token", "collateral_chain": "unbreakable_tether"},
    ),
    "Boardroom-Betrayal": _preset(
        default_name="Adrian Bell",
        archetype="The Corporate Betrayal",
        required_weights=("promotion_rivalry_heat", "workspace_proximity", "loyalty_friction_heat"),
        weights={
            "promotion_rivalry_heat": 5,
            "workspace_proximity": 4,
            "loyalty_friction_heat": 3,
            "angst_meter": 4,
            "lie_active": True,
            "lie_count": 2,
            "distance_locked": True,
        },
        environment_type="Boardroom annex behind a partition door after midnight summaries",
        incident_summary="Two longtime friends are competing for the same executive seat while one of them develops an attraction to the player's off-limits role inside the same corporate machine.",
        spark_token="A partition door slid shut over a table full of marked executive summaries.",
        unbreakable_tether="The attraction exists inside the same promotion fight that could end a friendship and reorder the entire firm's hierarchy.",
        phase_four_rule=(
            ("promotion_rivalry_heat", ">=", 4),
            ("loyalty_friction_heat", ">=", 3),
        ),
        dialogue_payload="He and I climbed the ranks of this firm together. We're supposed to be fighting for that vice-president seat, and you're supposed to be the untouchable assistant coordinating the files. But reviewing these midnight summaries side-by-side... I don't care if I tank our partnership contract.",
        action_prompt="They slide the partition door closed and lock their eyes on yours in the strip of half-dark between the blinds.",
        if_player_lied="Then I'll go back into the boardroom and let ambition eat the part of me that ever thought this was worth the cost.",
        if_player_honest="Then don't ask me to pretend this is just executive stress when I already know exactly which loss I'm more afraid of.",
        prompt_focus_keys=("promotion_rivalry_heat", "loyalty_friction_heat"),
        prompt_blurb="Keep the tone corporate and claustrophobic, with promotion warfare and friendship loyalty turning attraction into a career-grade betrayal.",
        legacy_aliases={"type": "environment_type", "promotion_war": "incident_summary", "partition": "spark_token", "board_seat": "unbreakable_tether"},
    ),
    "Enemies-Boardroom": _preset(
        default_name="Elian Cross",
        archetype="The Turf War",
        required_weights=(
            "performance_racing_heat",
            "hostile_friction_heat",
            "competence_respect",
        ),
        weights={
            "performance_racing_heat": 4,
            "hostile_friction_heat": 4,
            "competence_respect": 2,
            "angst_meter": 3,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": False,
        },
        environment_type="Late-night boardroom with two sets of revisions still glowing across the same contested table",
        incident_summary="A zero-sum corporate rivalry built on mocking edits, targeted account pressure, and mutual sabotage has turned into a fixation neither executive can admit without losing the last clean language they had for each other.",
        spark_token="An office chair wrenched around at the exact second the argument stops sounding professional.",
        unbreakable_tether="The more each side proves they can keep pace with the other, the harder it becomes to tell where performance warfare ends and admiration begins.",
        phase_four_rule=("competence_respect", ">=", 4),
        dialogue_payload="I spent six months trying to systematically target your accounts, mock your formatting guidelines, and tank your performance reviews because looking at you was the only thing that shattered my composure. I am utterly sick of this zero-sum warfare. Challenge me face-to-face.",
        action_prompt="They spin your office chair around and catch the armrests before you can escape the argument, jaw set like the confrontation finally stopped being about work.",
        if_player_lied="Then let's go back to burying this under memos and scorekeeping. At least performance war has rules stricter than whatever this became.",
        if_player_honest="Then stop asking me to keep calling this competition when the only part of the race I still care about is whether you look at me like an equal when the room is empty.",
        prompt_focus_keys=("hostile_friction_heat", "competence_respect"),
        prompt_blurb="Keep the tone sharp, sarcastic, and professionally territorial, with mutual excellence turning rivalry into the most dangerous form of respect.",
        legacy_aliases={"type": "environment_type", "account_war": "incident_summary", "chair_lock": "spark_token", "corporate_tether": "unbreakable_tether"},
    ),
}
