from __future__ import annotations

from .base import _preset


PRESETS = {
    "Babysitter": _preset(
        default_name="Poppy Wren",
        archetype="The Temporary Caretaker",
        required_weights=(
            "domestic_familiarity",
            "proximity_restraint",
            "caretaking_glow",
        ),
        weights={
            "domestic_familiarity": 4,
            "proximity_restraint": 3,
            "caretaking_glow": 2,
            "angst_meter": 2,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": True,
        },
        environment_type="Living room after the child finally falls asleep",
        incident_summary="An ordinary babysitting arrangement keeps creating late-night domestic quiet that makes the line between trusted helper and wanted person feel thinner every week.",
        spark_token="A half-finished dinosaur drawing left on the coffee table beside the sitter's overnight bag.",
        unbreakable_tether="Household trust, bedtime routine, and familiar access keep turning temporary care into emotional closeness.",
        phase_four_rule=("caretaking_glow", ">=", 4),
        dialogue_payload="I was supposed to make dinner, keep the kid alive, and wait for you to get home. I was not supposed to start measuring my week by whether I get these quiet twenty minutes alone with you after the house settles down.",
        action_prompt="They smooth the crayon drawing flat against the table and don't move when you step into the room.",
        if_player_lied="Then I'll keep being helpful and temporary. Temporary people are easier to send home.",
        if_player_honest="Then stop thanking me like a sitter you can dismiss at the front door and tell me why this feels different when it's just us awake.",
        prompt_focus_keys=("domestic_familiarity", "proximity_restraint"),
        prompt_blurb="Keep the mood intimate and household-scaled, with trust and routine making the attraction feel warm, risky, and harder to write off as a one-time spark.",
        legacy_aliases={"type": "environment_type", "babysitting": "incident_summary", "drawing": "spark_token", "routine": "unbreakable_tether"},
    ),
    "Nanny-Romance": _preset(
        default_name="Iris Calder",
        archetype="The Caretaker in the House",
        required_weights=(
            "domestic_attachment",
            "caretaking_tension",
            "household_intimacy",
        ),
        weights={
            "domestic_attachment": 4,
            "caretaking_tension": 4,
            "household_intimacy": 3,
            "angst_meter": 2,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": True,
        },
        environment_type="Quiet kitchen after the children are asleep",
        incident_summary="The household has become too small to hide how often care bleeds past the professional role.",
        spark_token="A plastic dinosaur clipped to the edge of their pocket notebook.",
        unbreakable_tether="Shared routines built around bedtime, breakfast, and every ordinary emergency in between.",
        phase_four_rule=("domestic_attachment", ">=", 4),
        dialogue_payload="I am supposed to care for this family without becoming part of it. So tell me why every time you thank me softly in this kitchen, it feels like I am already in too deep to leave cleanly.",
        action_prompt="They set the notebook down beside a baby monitor and stay standing much closer than the room requires.",
        if_player_lied="Then let me stay useful and invisible. I know how to survive in the role if that's all you need.",
        if_player_honest="Then stop thanking me like hired help and tell me whether you feel this home changing around us too.",
        prompt_focus_keys=("household_intimacy", "domestic_attachment"),
        prompt_blurb="Keep the tone competent and nurturing, with domestic routine turning professionalism into something warmer and much harder to contain.",
        legacy_aliases={"type": "environment_type", "household": "incident_summary", "notebook": "spark_token", "routine": "unbreakable_tether"},
    ),
    "Maid-Romance": _preset(
        default_name="Elara Finch",
        archetype="The Watchful Housekeeper",
        required_weights=(
            "service_hierarchy",
            "observant_intimacy",
            "class_restraint",
        ),
        weights={
            "service_hierarchy": 5,
            "observant_intimacy": 2,
            "class_restraint": 4,
            "angst_meter": 3,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": True,
        },
        environment_type="Upstairs corridor of a private estate",
        incident_summary="They know every habit in the house and all the places where your private life spills into their careful line of work.",
        spark_token="A linen handkerchief monogrammed with your family crest.",
        unbreakable_tether="A daily intimacy created by care work that is never supposed to become personal.",
        phase_four_rule=("observant_intimacy", ">=", 4),
        dialogue_payload="I know which floorboards you avoid when you're anxious and which glass you reach for when you cannot sleep. Please don't ask me to pretend that kind of knowledge is still impersonal.",
        action_prompt="They fold the monogrammed handkerchief once more, then leave it in your hand instead of returning it to the tray.",
        if_player_lied="Understood. I will keep the silver polished and my thoughts where they belong.",
        if_player_honest="Then stop looking through me like staff and tell me what you intend to do with how well I already know you.",
        prompt_focus_keys=("service_hierarchy", "observant_intimacy"),
        prompt_blurb="Use quiet observation, class boundaries, and domestic service details to make the attraction feel intimate, disciplined, and increasingly unsustainable.",
        legacy_aliases={"type": "environment_type", "estate": "incident_summary", "handkerchief": "spark_token", "service": "unbreakable_tether"},
    ),
    "Pool-Boy": _preset(
        default_name="Noah Sloane",
        archetype="The Summer Distraction",
        required_weights=(
            "sunlit_flirtation",
            "class_tension",
            "domestic_temptation",
        ),
        weights={
            "sunlit_flirtation": 4,
            "class_tension": 3,
            "domestic_temptation": 2,
            "angst_meter": 1,
            "lie_active": False,
            "lie_count": 0,
            "distance_locked": False,
        },
        environment_type="Poolside patio in heavy summer heat",
        incident_summary="Routine maintenance visits keep turning into charged, half-domestic encounters neither of you planned for.",
        spark_token="A damp service receipt curled at the edges from chlorine mist.",
        unbreakable_tether="A steady excuse to keep showing up at the same house under the same sun.",
        phase_four_rule=("domestic_temptation", ">=", 4),
        dialogue_payload="I keep telling myself I'm here to skim leaves and check the filter. Then you walk outside barefoot like that and suddenly this whole job starts feeling like a terrible excuse to look at you too long.",
        action_prompt="They tuck the damp receipt into a back pocket and lean the skimmer pole against the wall without taking their eyes off you.",
        if_player_lied="No problem. I'll clean the pool, nod politely, and leave the fantasy in the deep end where it belongs.",
        if_player_honest="Then stop acting like the heat is the only reason the air changes every time I show up here.",
        prompt_focus_keys=("sunlit_flirtation", "domestic_temptation"),
        prompt_blurb="Keep the dynamic warm, easy, and visibly physical, while ordinary household access turns casual attraction into something harder to shrug off.",
        legacy_aliases={"type": "environment_type", "service_call": "incident_summary", "receipt": "spark_token", "summer": "unbreakable_tether"},
    ),
    "Landscaper-Romance": _preset(
        default_name="Micah Reed",
        archetype="The Quiet Groundskeeper",
        required_weights=(
            "seasonal_proximity",
            "laboring_focus",
            "curbside_tension",
        ),
        weights={
            "seasonal_proximity": 4,
            "laboring_focus": 3,
            "curbside_tension": 2,
            "angst_meter": 1,
            "lie_active": False,
            "lie_count": 0,
            "distance_locked": False,
        },
        environment_type="Garden path outside a townhouse",
        incident_summary="Repeated work on the same property has created a quiet intimacy built out of seasons, habits, and unspoken looking.",
        spark_token="A pair of gardening gloves dusted with soil and crushed lavender.",
        unbreakable_tether="A landscape that keeps changing under both of your hands.",
        phase_four_rule=("curbside_tension", ">=", 4),
        dialogue_payload="I know every corner of this yard better than I know some people. But lately I keep lifting my head every few minutes just to check whether you're still watching from the porch.",
        action_prompt="They peel off one glove finger by finger and set it beside the lavender bed.",
        if_player_lied="Then I'll keep to the hedges and let the rest stay quiet.",
        if_player_honest="Then come down from the porch and stop making me guess whether I'm the only one feeling this grow.",
        prompt_focus_keys=("seasonal_proximity", "curbside_tension"),
        prompt_blurb="Use steady, seasonal repetition and grounded physical labor to make the attraction feel patient, local, and increasingly impossible to ignore.",
        legacy_aliases={"type": "environment_type", "grounds": "incident_summary", "gloves": "spark_token", "season": "unbreakable_tether"},
    ),
}
