from __future__ import annotations

from .base import _preset


PRESETS = {
    "Billionaire-Playboy": _preset(
        default_name="Julian Moreau",
        archetype="The Corporate Playmaker",
        required_weights=(
            "capital_leverage",
            "media_scrutiny_heat",
            "exclusive_fixation",
        ),
        weights={
            "capital_leverage": 5,
            "media_scrutiny_heat": 4,
            "exclusive_fixation": 1,
            "angst_meter": 1,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": False,
        },
        environment_type="Town car sealed off from the gala flashbulbs",
        incident_summary="A media-trained playboy facade kept shareholders calm and tabloids fed until one private fixation made the public script feel unbearable.",
        spark_token="A privacy partition clicked shut between the car and the paparazzi.",
        unbreakable_tether="A life built on public performance that suddenly has only one person worth dropping the act for.",
        phase_four_rule=("exclusive_fixation", ">=", 4),
        dialogue_payload="The tabloids can photograph me with every heiress in Europe. It's just calculated public relations to keep the share price stable. But when the flashbulbs fade and I'm sitting in the back of this car... you are the only asset I actually care about holding. I am done playing the playboy.",
        action_prompt="They slide the town car's privacy partition closed with a hard click and catch your hand before you can pull away.",
        if_player_lied="Then I can reopen the partition and let the cameras have the version of me they understand.",
        if_player_honest="Then don't ask me to keep performing detachment when I've already chosen you over the whole spectacle.",
        prompt_focus_keys=("media_scrutiny_heat", "exclusive_fixation"),
        prompt_blurb="Use public playboy polish, wealth, and media calculation as armor, then let possessive private fixation strip that armor away in isolated moments.",
        legacy_aliases={"type": "environment_type", "judgment": "incident_summary", "generation_token": "spark_token", "future_pull": "unbreakable_tether"},
    ),
    "Corporate-Playmaker": _preset(
        default_name="Julian Moreau",
        archetype="The Corporate Playmaker",
        required_weights=(
            "capital_leverage",
            "media_scrutiny_heat",
            "exclusive_fixation",
        ),
        weights={
            "capital_leverage": 5,
            "media_scrutiny_heat": 4,
            "exclusive_fixation": 1,
            "angst_meter": 1,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": False,
        },
        environment_type="Town car sealed off from the gala flashbulbs",
        incident_summary="A board-approved playboy persona kept the markets calm and the tabloids predictable until private exclusivity broke through the performance layer.",
        spark_token="A privacy partition clicked shut between the car and the outside lenses.",
        unbreakable_tether="A public image built for everyone and a private fixation that only wants one person behind the glass.",
        phase_four_rule=("exclusive_fixation", ">=", 4),
        dialogue_payload="The tabloids can photograph me with every heiress in Europe. It's just calculated public relations to keep the share price stable. But when the flashbulbs fade and I'm sitting in the back of this car... you are the only asset I actually care about holding. I am done playing the playboy.",
        action_prompt="They seal the partition and pull your hand into their lap before the outside noise can leak back in.",
        if_player_lied="Then I'll put the mask back on and keep giving the market what it expects from me.",
        if_player_honest="Then stop making me split myself in two. The public act is dead the second you look at me like that.",
        prompt_focus_keys=("media_scrutiny_heat", "exclusive_fixation"),
        prompt_blurb="Keep the voice polished, expensive, and PR-conscious until the private fixation becomes more important than the entire public machine.",
        legacy_aliases={"type": "environment_type", "publicity": "incident_summary", "partition": "spark_token", "share_price": "unbreakable_tether"},
    ),
    "Crown-Advisor": _preset(
        default_name="Cassian Vale",
        archetype="The Crown Advisor",
        required_weights=(
            "political_restraint_index",
            "syndicate_honor_code",
            "protective_shield_drive",
        ),
        weights={
            "political_restraint_index": 5,
            "syndicate_honor_code": 4,
            "protective_shield_drive": 3,
            "angst_meter": 4,
            "lie_active": False,
            "lie_count": 0,
            "distance_locked": True,
        },
        environment_type="Council chamber at the center of a dangerous court",
        incident_summary="An older advisor's duty to the young ruler was supposed to remain cold, strategic, and ceremonial until palace danger transformed it into something fiercely personal.",
        spark_token="A ceremonial sidearm drawn across the council threshold.",
        unbreakable_tether="A structure of duty and rank that turns every protective impulse into both proof of loyalty and evidence of dangerous attachment.",
        phase_four_rule=("protective_shield_drive", ">=", 4),
        dialogue_payload="I was appointed to guide your throne, monitor your councilors, and ensure your lineage stays protected from the court vipers. My duty is an unyielding, cold shield. But you aren't listening to my tactical advice anymore, and I am going to end up executing half this room before I let anyone touch you.",
        action_prompt="They step out of the guard line, ceremonial weapon drawn, and block the council doors with their whole body.",
        if_player_lied="Then I'll sheath the weapon and pretend duty still feels simple, even though you made that impossible a long time ago.",
        if_player_honest="Then stop calling this only loyalty. I crossed that line the moment your safety started mattering more than the crown itself.",
        prompt_focus_keys=("political_restraint_index", "protective_shield_drive"),
        prompt_blurb="Use duty, hierarchy, and court danger to make protectiveness feel both politically necessary and emotionally unsustainable.",
        legacy_aliases={"type": "environment_type", "court": "incident_summary", "sidearm": "spark_token", "throne": "unbreakable_tether"},
    ),
    "Century-Void": _preset(
        default_name="Lucien Ash",
        archetype="The Ageless Immortal",
        required_weights=(
            "century_void_variance",
            "emotional_detachment",
            "fear_of_inevitable_loss",
        ),
        weights={
            "century_void_variance": 5,
            "emotional_detachment": 4,
            "fear_of_inevitable_loss": 4,
            "angst_meter": 5,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": False,
        },
        environment_type="Stone balcony overlooking a city that has outlived empires",
        incident_summary="A centuries-old being tried to keep a mortal companion at observational distance until the certainty of future loss turned detachment into a failing strategy.",
        spark_token="An ice-cold hand lifted to a mortal jaw in a moment of surrender.",
        unbreakable_tether="A love haunted by time itself, where one heart is transient and the other has already survived too much to stay whole.",
        phase_four_rule=("fear_of_inevitable_loss", ">=", 5),
        dialogue_payload="I have watched empires turn to dust, cities collapse into ruins, and entire generations fade away without my pulse shifting a single beat. My life is an endless, cold void. Loving you is a death sentence for my composure, because your mortality is ticking down, and I am entirely finished playing the detached observer.",
        action_prompt="They close the distance in a soundless step and settle an ice-cold hand against your jaw as though that touch alone could stop time.",
        if_player_lied="Then let me go back to the emptiness that kept me intact before you taught me what a future could cost.",
        if_player_honest="Then don't ask me to be calm about the clock. I already know exactly how much time is capable of taking.",
        prompt_focus_keys=("emotional_detachment", "fear_of_inevitable_loss"),
        prompt_blurb="Keep the voice ancient, controlled, and grief-shaped, with attraction rendered terrifying because immortality guarantees witness to loss.",
        legacy_aliases={"type": "environment_type", "immortality": "incident_summary", "cold_hand": "spark_token", "mortality": "unbreakable_tether"},
    ),
    "Charitable-Proxy": _preset(
        default_name="Celeste Moreau",
        archetype="The Philanthropist Target",
        required_weights=(
            "funding_leverage_heat",
            "charitable_proxy_shield",
            "exposure_panic_index",
        ),
        weights={
            "funding_leverage_heat": 4,
            "charitable_proxy_shield": 4,
            "exposure_panic_index": 2,
            "angst_meter": 2,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": False,
        },
        environment_type="Glass conference table inside the foundation wing",
        incident_summary="A billionaire used grants, endowments, and philanthropic cover to create proximity that looked socially virtuous until the hidden motive became impossible to hide.",
        spark_token="Grant authorization papers thrown onto polished glass.",
        unbreakable_tether="A connection engineered through respectable money, where every act of generosity carries the risk of exposure.",
        phase_four_rule=("exposure_panic_index", ">=", 4),
        dialogue_payload="You think I endowed this research foundation and funded your gallery project because I care about the art indices? I did it because it was the only calculated loop that would make you sit at my table every afternoon. I bought the entire complex just to hear you explain your ideas.",
        action_prompt="They toss the authorization documents onto the table, their philanthropic smile disappearing in one brittle breath.",
        if_player_lied="Then I'll keep pretending this was altruism and let the foundation absorb the lie for me.",
        if_player_honest="Then don't ask me to hide behind generosity when we both know I built this whole structure just to stay near you.",
        prompt_focus_keys=("charitable_proxy_shield", "exposure_panic_index"),
        prompt_blurb="Use elegant philanthropy and funding leverage as a respectable mask for obsession, then let exposure panic rupture the polish.",
        legacy_aliases={"type": "environment_type", "grant": "incident_summary", "documents": "spark_token", "foundation": "unbreakable_tether"},
    ),
    "Algorithmic-Drive": _preset(
        default_name="Theo Vale",
        archetype="The Silicon Valley Tech Mogul",
        required_weights=(
            "digital_metric_control",
            "algorithmic_proximity",
            "surveillance_paranoia",
        ),
        weights={
            "digital_metric_control": 5,
            "algorithmic_proximity": 4,
            "surveillance_paranoia": 3,
            "angst_meter": 2,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": True,
        },
        environment_type="Server room wrapped around a central monitoring desk",
        incident_summary="A tech mogul treated proximity like a system problem to optimize, using infrastructure and data visibility to close distance until the human variable stopped obeying the model.",
        spark_token="A central console powered down hard enough to erase the glow.",
        unbreakable_tether="A connection built through total systems control that starts failing the second the mogul feels something unquantifiable.",
        phase_four_rule=("algorithmic_proximity", ">=", 5),
        dialogue_payload="I built the mainframes that process half the communication data streams on this coast. I can code a script to predict stock fluctuations or manipulate media feeds in minutes. I treated your dating profile like a data pattern to optimize. But standing in this server room next to you... my entire logic model just crashed.",
        action_prompt="They cut power to the monitoring desk, dropping the room into darkness as they step toward you.",
        if_player_lied="Then I'll reboot the system and let the model tell me I imagined the whole deviation.",
        if_player_honest="Then don't ask me to retreat into code when you're the first variable I've ever wanted precisely because I couldn't control it.",
        prompt_focus_keys=("digital_metric_control", "algorithmic_proximity"),
        prompt_blurb="Keep the tone hyper-rational and surveillance-aware, then let the breakdown of control feel intimate, embarrassing, and irreversible.",
        legacy_aliases={"type": "environment_type", "data": "incident_summary", "console": "spark_token", "mainframe": "unbreakable_tether"},
    ),
    "Lineage-Shield": _preset(
        default_name="Adrian Moreau",
        archetype="The Old Money Aristocrat",
        required_weights=(
            "generational_asset_weight",
            "lineage_honor_code",
            "systemic_restraint",
        ),
        weights={
            "generational_asset_weight": 5,
            "lineage_honor_code": 4,
            "systemic_restraint": 3,
            "angst_meter": 4,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": False,
        },
        environment_type="Marble dining room in the family estate",
        incident_summary="Old money lineage and family institutions forced the character into chilly precision while the desire to protect a civilian from that same machine kept breaking the facade.",
        spark_token="A family signet ring laid flat on cold marble.",
        unbreakable_tether="A bond strained by inheritance, family scrutiny, and the threat of being absorbed into a system older than either of you can fight cleanly.",
        phase_four_rule=("systemic_restraint", ">=", 4),
        dialogue_payload="My family's trust fund has ruled this city's institutions for two centuries, and my name is tied to a dozen board metrics. I played the detached, clinical aristocrat to protect you from their lawyers. But I would slide my entire inheritance across this table and walk away from the estate before I let them dictate who I hold onto.",
        action_prompt="They slide the signet ring off and place it on the table like a declaration of war against their own bloodline.",
        if_player_lied="Then I'll put the ring back on and let the family keep mistaking obedience for loyalty.",
        if_player_honest="Then don't make me pretend the estate matters more than you when I'm already halfway to burning the bridge myself.",
        prompt_focus_keys=("lineage_honor_code", "systemic_restraint"),
        prompt_blurb="Use old-money formality, family machinery, and inheritance pressure to make every tender choice feel expensive and defiant.",
        legacy_aliases={"type": "environment_type", "estate": "incident_summary", "ring": "spark_token", "inheritance": "unbreakable_tether"},
    ),
    "Luxury-Confinement": _preset(
        default_name="Julian Moreau",
        archetype="The Velvet Cage",
        required_weights=(
            "luxury_isolation_lock",
            "spatial_confinement",
            "detachment_erosion_heat",
        ),
        weights={
            "luxury_isolation_lock": 5,
            "spatial_confinement": 4,
            "detachment_erosion_heat": 2,
            "angst_meter": 3,
            "lie_active": False,
            "lie_count": 0,
            "distance_locked": True,
        },
        environment_type="Private island terrace above a sealed compound",
        incident_summary="Extreme luxury and remote security turned isolation into a gilded trap, where the billionaire's detachment began eroding into mutual dependency.",
        spark_token="A compound keycard tossed into black water below the terrace.",
        unbreakable_tether="A paradise built to control noise, distance, and access until the person inside it becomes the only thing the owner can't manage cleanly.",
        phase_four_rule=("detachment_erosion_heat", ">=", 4),
        dialogue_payload="I built this entire estate three hundred miles from the nearest mainland radar to escape the noise. I have the capital to keep you locked inside this paradise indefinitely without a single tracking code leaking. But sitting on this terrace... I realize I am the one who is completely trapped in your space.",
        action_prompt="They slam the glass slider shut and throw the security keycard into the sea without looking away from you.",
        if_player_lied="Then the island can keep both of us in our cages and I can pretend the bars were always the point.",
        if_player_honest="Then don't ask me to call this captivity when you're the first thing here that has ever felt more dangerous than freedom.",
        prompt_focus_keys=("spatial_confinement", "detachment_erosion_heat"),
        prompt_blurb="Keep the tone luxurious, isolated, and subtly coercive, with detachment failing under the weight of confinement and private dependence.",
        legacy_aliases={"type": "environment_type", "island": "incident_summary", "keycard": "spark_token", "compound": "unbreakable_tether"},
    ),
    "Retainer-Date": _preset(
        default_name="Julian Moreau",
        archetype="The High-Value Escort",
        required_weights=(
            "transactional_boundary",
            "performative_warmth_mask",
            "contractual_lock_friction",
        ),
        weights={
            "transactional_boundary": 5,
            "performative_warmth_mask": 4,
            "contractual_lock_friction": 2,
            "angst_meter": 3,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": False,
        },
        environment_type="Private dining room after the corporate event ended",
        incident_summary="A billionaire funded a recurring retainer to buy a perfect public illusion, only to find the contract structure collapsing the minute private feeling became unavoidable.",
        spark_token="A premium invoice copy shredded while the night is still warm.",
        unbreakable_tether="A relationship built on a ledger that stops feeling stable the moment the performance ends and nobody leaves.",
        phase_four_rule=("contractual_lock_friction", ">=", 4),
        dialogue_payload="I funded your agency's retainer invoices so I could buy a seamless public illusion and avoid having to manage real vulnerability. I owned the timetable. But the corporate dinner concluded two hours ago, the ledger is closed, and I am going to tear up our contract because I can't let you check out.",
        action_prompt="They feed the invoice through the shredder with white knuckles, then close the distance before the last strip falls.",
        if_player_lied="Then I'll pay for the silence and call this another premium service successfully rendered.",
        if_player_honest="Then don't ask me to hide behind invoices when I'm already destroying the only excuse that kept this emotionally clean.",
        prompt_focus_keys=("performative_warmth_mask", "contractual_lock_friction"),
        prompt_blurb="Use public polish, payment structure, and post-event quiet to make the collapse from transaction into genuine need feel sharp and destabilizing.",
        legacy_aliases={"type": "environment_type", "retainer": "incident_summary", "invoice": "spark_token", "ledger": "unbreakable_tether"},
    ),
    "Starlet-Shield": _preset(
        default_name="Vivian Cross",
        archetype="The Hollywood A-Lister",
        required_weights=(
            "media_scrutiny_panic",
            "stardom_performance_mask",
            "protective_shield_drive",
        ),
        weights={
            "media_scrutiny_panic": 5,
            "stardom_performance_mask": 4,
            "protective_shield_drive": 3,
            "angst_meter": 4,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": True,
        },
        environment_type="Master suite behind blackout mansion draperies",
        incident_summary="Extreme visibility forced the celebrity into constant performance until protecting one private civilian bond became more important than the contract holding the whole persona together.",
        spark_token="Heavy blackout drapes drawn against a bank of tracking lenses.",
        unbreakable_tether="A hidden relationship protected by logistics, shadows, and the increasingly desperate need to keep the outside machine away from what matters.",
        phase_four_rule=("protective_shield_drive", ">=", 4),
        dialogue_payload="My name is on billboards across this city, and my entire life is monitored by tracking lenses and paparazzi arrays. It's an exhausting, performative matrix. But checking the gate monitors today and seeing them target your car... I am ready to walk off the set and burn my entire contract before I let them touch you.",
        action_prompt="They drag the blackout draperies fully shut, dropping the room into shadow before stepping directly into your space.",
        if_player_lied="Then I'll reopen the curtains and let the machine have me back. It already knows how to consume easier things than this.",
        if_player_honest="Then don't ask me to keep performing calm when every spotlight in this city suddenly feels like a threat to you.",
        prompt_focus_keys=("media_scrutiny_panic", "protective_shield_drive"),
        prompt_blurb="Play celebrity as a surveillance burden, with private protection becoming frantic and personal the second the outside gaze turns toward the relationship.",
        legacy_aliases={"type": "environment_type", "paparazzi": "incident_summary", "drapes": "spark_token", "contract": "unbreakable_tether"},
    ),
    "Celebrity-Ordinary-Person": _preset(
        default_name="Vivian Cross",
        archetype="The Spotlight Escape",
        required_weights=("fame_pressure", "normalcy_craving", "paparazzi_panic"),
        weights={
            "fame_pressure": 5,
            "normalcy_craving": 3,
            "paparazzi_panic": 3,
            "angst_meter": 3,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": False,
        },
        environment_type="Back alley behind a theater premiere",
        incident_summary="One ordinary person keeps becoming the only place where celebrity stops feeling like an identity and starts feeling like a prison.",
        spark_token="A baseball cap borrowed in a hurry to hide from cameras.",
        unbreakable_tether="A private refuge inside a life where almost nothing stays private.",
        phase_four_rule=("normalcy_craving", ">=", 4),
        dialogue_payload="You treat me like a person so naturally it almost feels violent. I don't know what to do with a kind of attention that isn't trying to own a piece of me.",
        action_prompt="They pull the borrowed cap lower over their face and lean closer to keep out of the light.",
        if_player_lied="Then let me keep performing. Performance is easier than hoping this could stay human.",
        if_player_honest="Then don't ask for the version of me the cameras built. I only know how to offer you the one hiding behind this cap.",
        prompt_focus_keys=("fame_pressure", "normalcy_craving"),
        prompt_blurb="Keep fame heavy and dehumanizing, with ordinary treatment feeling more intimate than overt seduction.",
        legacy_aliases={"type": "environment_type", "premiere": "incident_summary", "cap": "spark_token", "privacy": "unbreakable_tether"},
    ),
    "Movie-Star-Commoner": _preset(
        default_name="Eden Vale",
        archetype="The Off-Camera Escape",
        required_weights=("fame_pressure", "normalcy_craving", "paparazzi_panic"),
        weights={
            "fame_pressure": 5,
            "normalcy_craving": 3,
            "paparazzi_panic": 3,
            "angst_meter": 3,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": False,
        },
        environment_type="Back exit behind a premiere theater",
        incident_summary="A superstar used one ordinary conversation with you as shelter from a life that turns every glance into marketable footage.",
        spark_token="A pair of sunglasses abandoned in your passenger seat.",
        unbreakable_tether="The single private space where fame stops feeling like armor and starts feeling like a wound.",
        phase_four_rule=("normalcy_craving", ">=", 4),
        dialogue_payload="Do you know how rare it is for someone to look at me and not immediately start calculating what I can do for their life? I keep coming back because being ordinary beside you feels dangerously close to peace.",
        action_prompt="They shove the sunglasses into their pocket and keep scanning the alley for cameras anyway.",
        if_player_lied="Fine. We can call this a fun story and let the headlines keep owning the rest of me.",
        if_player_honest="Then don't ask for the version of me everyone else gets. I am only offering you the one that exists after the flashbulbs die.",
        prompt_focus_keys=("fame_pressure", "normalcy_craving"),
        prompt_blurb="Treat celebrity as a cage, and let the character cling to the player's ordinariness as the only place where desire can feel unscripted.",
        legacy_aliases={"type": "environment_type", "premiere": "incident_summary", "sunglasses": "spark_token", "flashbulbs": "unbreakable_tether"},
    ),
    "Romance-On-Set": _preset(
        default_name="Cassian Rowe",
        archetype="The Script Bleed",
        required_weights=("scripted_intimacy", "publicity_spin", "between_takes_tension"),
        weights={
            "scripted_intimacy": 4,
            "publicity_spin": 3,
            "between_takes_tension": 2,
            "angst_meter": 2,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": True,
        },
        environment_type="Closed soundstage under false rain",
        incident_summary="Repeated scene work has blurred the line between performed chemistry and private want.",
        spark_token="A page of sides marked with blocking notes and lipstick smears.",
        unbreakable_tether="Every retake forces the same touch, the same line, and less distance between the truth and the script.",
        phase_four_rule=("between_takes_tension", ">=", 4),
        dialogue_payload="I can hit every mark, kiss you on cue, and sell it to the camera without breaking. It's the silence after the director says cut that is starting to ruin me.",
        action_prompt="They drop the marked-up script to their side and forget the crew still exists for one full breath.",
        if_player_lied="Then let's keep giving them the version they paid for and leave the rest on the floor with the tape marks.",
        if_player_honest="Then stop calling it chemistry workshopping and tell me whether you feel the same thing when the cameras aren't rolling.",
        prompt_focus_keys=("scripted_intimacy", "between_takes_tension"),
        prompt_blurb="Keep the voice professional in public, but let rehearsal repetition and staged kisses make private restraint harder to maintain after every cut.",
        legacy_aliases={"type": "environment_type", "production": "incident_summary", "sides": "spark_token", "retake": "unbreakable_tether"},
    ),
    "Rich-Poor": _preset(
        default_name="Julian Moreau",
        archetype="The Uneven Fortune",
        required_weights=("class_imbalance", "resource_insecurity", "protective_generosity"),
        weights={
            "class_imbalance": 5,
            "resource_insecurity": 3,
            "protective_generosity": 2,
            "angst_meter": 3,
            "lie_active": False,
            "lie_count": 0,
            "distance_locked": False,
        },
        environment_type="Townhouse kitchen after a charity gala",
        incident_summary="Every attraction is filtered through money, access, and the terror of what help looks like when one person can solve problems the other can barely name aloud.",
        spark_token="A charity auction paddle still tucked into a back pocket.",
        unbreakable_tether="The constant question of whether care can survive a power imbalance built into daily life.",
        phase_four_rule=("protective_generosity", ">=", 4),
        dialogue_payload="I can cover every bill in this room without blinking, and I hate how much that changes the way you look at any kindness I offer. Tell me how to take care of you without making you feel purchased.",
        action_prompt="They set the auction paddle on the counter like a weapon they regret bringing home.",
        if_player_lied="Then let's make it clean. No help, no debts, no pretending money doesn't bend everything around it.",
        if_player_honest="Then let me show you generosity that doesn't ask you to kneel to it.",
        prompt_focus_keys=("class_imbalance", "protective_generosity"),
        prompt_blurb="Keep money as an active pressure source, with generosity threatening to feel coercive unless the character learns to offer care without ownership.",
        legacy_aliases={"type": "environment_type", "divide": "incident_summary", "paddle": "spark_token", "money": "unbreakable_tether"},
    ),
    "Rockstar-Romance": _preset(
        default_name="Jace Wilder",
        archetype="The Stage-Burned Confessor",
        required_weights=("touring_chaos", "crowd_possessiveness", "backstage_vulnerability"),
        weights={
            "touring_chaos": 4,
            "crowd_possessiveness": 3,
            "backstage_vulnerability": 2,
            "angst_meter": 2,
            "lie_active": False,
            "lie_count": 0,
            "distance_locked": False,
        },
        environment_type="Backstage green room after an encore",
        incident_summary="The stage gives them absolute command until the lights die and all that remains is the person they wanted to find in the wings.",
        spark_token="A guitar pick snapped clean through the middle.",
        unbreakable_tether="A pattern of leaving the crowd still screaming just to come apart somewhere quieter with you.",
        phase_four_rule=("backstage_vulnerability", ">=", 4),
        dialogue_payload="I can have ten thousand people chanting my name and still walk offstage feeling empty. Then I see you behind the curtain and suddenly every song sounds like a confession I haven't finished yet.",
        action_prompt="They drag a hand through sweat-damp hair and lean the broken pick into your palm.",
        if_player_lied="Then keep me where the crowd keeps me. They're loud enough that I don't have to hear what I actually want.",
        if_player_honest="Then come closer before the adrenaline burns off and I remember how to hide again.",
        prompt_focus_keys=("crowd_possessiveness", "backstage_vulnerability"),
        prompt_blurb="Let public charisma mask a private crash, with performance highs turning into exposed need the second the player reaches the backstage side of the door.",
        legacy_aliases={"type": "environment_type", "encore": "incident_summary", "guitar_pick": "spark_token", "tour": "unbreakable_tether"},
    ),
    "Cinderella-Circumstance": _preset(
        default_name="Maris Vale",
        archetype="The Midnight Escape",
        required_weights=("class_disparity", "midnight_expiry_panic", "transformative_allure"),
        weights={
            "class_disparity": 4,
            "midnight_expiry_panic": 3,
            "transformative_allure": 2,
            "angst_meter": 2,
            "lie_active": True,
            "lie_count": 1,
            "distance_locked": False,
        },
        environment_type="Charity ball staircase",
        incident_summary="A borrowed night of impossible glamour has to end before the life underneath it becomes visible.",
        spark_token="One crystal heel strap hanging loose from a rushed descent.",
        unbreakable_tether="A perfect evening with an expiration time built directly into it.",
        phase_four_rule=("transformative_allure", ">=", 4),
        dialogue_payload="You are looking at me like I can stay lit like this forever, and I need you to understand that midnight is coming for me whether I beg it to or not.",
        action_prompt="They clutch the borrowed shoe in one hand and glance toward the dark service exit.",
        if_player_lied="Then remember the dress, not the girl underneath it. That's safer for both of us.",
        if_player_honest="Then find me after the glitter is gone and tell me whether I still look worth choosing.",
        prompt_focus_keys=("midnight_expiry_panic", "transformative_allure"),
        prompt_blurb="Keep the fantasy alive but fragile, with class anxiety and the threat of the spell ending pushing urgency into every tender moment.",
        legacy_aliases={"type": "environment_type", "ball": "incident_summary", "heel": "spark_token", "midnight": "unbreakable_tether"},
    ),
}
